version: '3.8'

services:
  ### Zookeeper ###
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zookeeper/zookeeper-data:/var/lib/zookeeper/data
      - ./zookeeper/zookeeper-log:/var/lib/zookeeper/log

  ### Kafka ###
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 10s
      retries: 5

  ### Neo4j ###
  neo4j:
    image: neo4j/neo4j-arm64-experimental:3.5.33-arm64
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_auth_enabled=false
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_connectors_default_listen_address=0.0.0.0
      - NEO4J_dbms_connector_http_listen_address=0.0.0.0:7474
      - NEO4J_dbms_connector_https_listen_address=0.0.0.0:7473
      - NEO4J_dbms_connector_bolt_listen_address=0.0.0.0:7687
    volumes:
      - ./neo4j/neo4j_data:/data
      - ./neo4j/neo4j_logs:/logs
      - ./neo4j/neo4j_import:/import
      - ./neo4j/neo4j_plugins:/plugins
    restart: unless-stopped

  ### Flink ###
  jobmanager:
    image: flink:1.19.0
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
    networks:
      - doris-lineage

  taskmanager:
    image: flink:1.19.0
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - doris-lineage
    deploy:
      replicas: 2

  ### Doris ###
  doris:
    image: yagagagaga/doris-standalone:2.1.5
    ports:
      - "8030:8030"
      - "8040:8040"
      - "9030:9030"
#    environment:
#      - BACKEND_LISTEN_HOST=0.0.0.0
    volumes:
      - ./doris/doris_fe_meta:/opt/doris/fe/meta
      - ./doris/doris_be_storage:/opt/doris/be/storage
    networks:
      - doris-lineage

  ### Schema Registry ###
  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - kafka

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  doris_fe_meta:
  doris_be_storage:

networks:
  doris-lineage:
    driver: bridge
